name: ActionImage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Github Registry
        uses: docker/build-push-action@v1
        with:
          path: ./src
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: shynixn/m2/deploy-action-base
          tag_with_ref: true  
