name: TestDeployment

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deploy-Sample-App:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build Java Application
        run: |
          cd sample-hello-world
          chmod +x gradlew
          ./gradlew build
          cd ..

      - name: Deploy Artifact
        uses: Shynixn/repository-m2-deploy-action@v1.0.16
        with:
          primary-jar-file: 'sample-hello-world/build/libs/sample-hello-world-1.0.0.jar' # The final jar can have any arbitrary name format, the jar file is automatically renamed according to the maven.
          group-id: 'com.github.shynixn.samplehelloworld'
          artifact-id: 'sample-hello-world'
          version-id: 1.0.${GITHUB_RUN_NUMBER} # We use the provided github run number to automatically create new releases.
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # We need to create a new personal access token and cannot use GITHUB_TOKEN because the GITHUB_TOKEN does not have permissions to post to other private repositories.
          github-username: 'Shynixn'
          github-repository: 'm2'
